apiVersion: v1
kind: Service
metadata:
  # A unique name for your service object
  name: multiplier-app-service
spec:
  # 'NodePort' exposes the service on a static port on each node's IP.
  # This is ideal for a 'kind' cluster.
  type: NodePort
  selector:
    # This selector must match the 'app' label on your Pods to find them.
    app: multiplier-app
  ports:
    - protocol: TCP
      # The port the service itself listens on internally. 80 is standard for HTTP.
      port: 80
      # The port on your container that traffic should be forwarded to.
      targetPort: 8000
      # The static port opened on your VM's IP address.
      # I've chosen 30084, assuming your other apps use 30080-30083.
      # This must be in the default range (30000-32767).
      nodePort: 30084